#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Ace_Pepper_House"
  https://create.arduino.cc/cloud/things/7ff91eeb-8c4b-4f96-bbf3-78c887f77e65 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSwitch treat;
  CloudTemperatureSensor insideTemperature;
  CloudTemperatureSensor outSideTemperature;
  CloudSwitch food;
  CloudDimmedLight light;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}

void onTreatChange() {
  // Do something
}

void onFoodChange() {
  // Do something
}

void onLightChange() {
  // Do something
}
