// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]           = "7ff91eeb-8c4b-4f96-bbf3-78c887f77e65";
const char DEVICE_LOGIN_NAME[]  = "6d260b23-7f5f-4f60-ac3e-fb5baded0adb";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onTreatChange();
void onFoodChange();
void onLightChange();

CloudSwitch treat;
CloudTemperatureSensor insideTemperature;
CloudTemperatureSensor outSideTemperature;
CloudSwitch food;
CloudDimmedLight light;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(treat, READWRITE, ON_CHANGE, onTreatChange);
  ArduinoCloud.addProperty(insideTemperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(outSideTemperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(food, READWRITE, ON_CHANGE, onFoodChange);
  ArduinoCloud.addProperty(light, READWRITE, ON_CHANGE, onLightChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
